name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout three.js base
      uses: actions/checkout@v2
      continue-on-error: true
      with:
        path: threejs

    - name: Checkout test tasks
      uses: actions/checkout@v2
      continue-on-error: true
      with:
        repository: 3jsLive/tasks
        token: ${{ secrets.GitHub_PAT }}
        path: tasks

    - name: install and build
      run: |
        cd $GITHUB_WORKSPACE
        cd threejs
        npm install
        npm run-script build
        cd ../tasks/checks
        npm install
        
    - name: run checks
      run: |
        cd $GITHUB_WORKSPACE
        cd tasks/checks
        node src/checkDocsForBrokenExampleLinks.js $GITHUB_WORKSPACE/threejs output.log

    - name: Archive results
      uses: actions/upload-artifact@v1
      with:
        name: broken examples
        path: tasks/checks/output.log
