name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout three.js base
      continue-on-error: true
      with:
        path: threejs

    - name: Checkout test tasks
    - uses: actions/checkout@v2
      continue-on-error: true
      with:
        repository: 3jsLive/tasks
        token: ${{ secrets.GitHub_PAT }}
        path: tasks

    - name: recon
      run: tree
