name: task tests, the inefficient way

on: [push]

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout three.js base
      uses: actions/checkout@v2
      continue-on-error: true
      with:
        path: threejs

    - name: Checkout test tasks
      uses: actions/checkout@v2
      continue-on-error: true
      with:
        repository: 3jsLive/tasks
        token: ${{ secrets.GitHub_PAT }}
        path: tasks

    - name: install and build
      run: |
        cd $GITHUB_WORKSPACE
        cd threejs
        npm install
        npm run-script build
        cd ../tasks/typesearch
        npm install
      
    - name: run typesearch
      run: |
        cd $GITHUB_WORKSPACE
        mkdir results
        cd $GITHUB_WORKSPACE/threejs
        python3 -m http.server -b localhost 14227 &
        cd $GITHUB_WORKSPACE/tasks/typesearch
        export typesearch_dataPath=$GITHUB_WORKSPACE/results
        DISPLAY=99 xvfb-run -a --server-args="-screen 0 1024x768x24 -ac -nolisten tcp -dpi 96 +extension GLX +extension RENDER +extension RANDR" node src/cli.js $GITHUB_WORKSPACE/eeeeverything/threejs 'http://127.0.0.1:14227/examples/css3d_sprites.html'

    - name: Archive results
      uses: actions/upload-artifact@v1
      with:
        name: typesearch1
        path: $GITHUB_WORKSPACE/results
  two:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout three.js base
      uses: actions/checkout@v2
      continue-on-error: true
      with:
        path: threejs

    - name: Checkout test tasks
      uses: actions/checkout@v2
      continue-on-error: true
      with:
        repository: 3jsLive/tasks
        token: ${{ secrets.GitHub_PAT }}
        path: tasks

    - name: install and build
      run: |
        cd $GITHUB_WORKSPACE
        cd threejs
        npm install
        npm run-script build
        cd ../tasks/typesearch
        npm install
      
    - name: run typesearch
      run: |
        cd $GITHUB_WORKSPACE
        mkdir results
        cd $GITHUB_WORKSPACE/threejs
        python3 -m http.server -b localhost 14227 &
        cd $GITHUB_WORKSPACE/tasks/typesearch
        export typesearch_dataPath=$GITHUB_WORKSPACE/results
        DISPLAY=99 xvfb-run -a --server-args="-screen 0 1024x768x24 -ac -nolisten tcp -dpi 96 +extension GLX +extension RENDER +extension RANDR" node src/cli.js $GITHUB_WORKSPACE/eeeeverything/threejs 'http://127.0.0.1:14227/examples/css3d_sprites.html'

    - name: Archive results
      uses: actions/upload-artifact@v1
      with:
        name: typesearch2
        path: $GITHUB_WORKSPACE/results
