name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout three.js base
      uses: actions/checkout@v2
      continue-on-error: true
      with:
        path: threejs

    - name: Checkout test tasks
      uses: actions/checkout@v2
      continue-on-error: true
      with:
        repository: 3jsLive/tasks
        token: ${{ secrets.GitHub_PAT }}
        path: tasks

    - name: recon
      run: |
        sudo apt install tree
        tree
